app/pictures/__init__.py
from flask import Blueprint

pictures = Blueprint('pictures', __name__, template_folder='templates')

import views

app/pictures/views.py
from flask import Blueprint, render_template, g
from flask_login import current_user, login_required, login_user, \
    logout_user
import glob
import os

from app import app
from app.pictures import pictures
from app.models import User, Message, Post


@pictures.before_request
def before_request():
    g.user = current_user


# @pictures.route('/photos')
# @login_required
# def pictures():
#     user_count = len(User.query.all())
#     new_message = len(Message.query.filter(Message.recipient == g.user.handle).filter(Message.read is False).all()) or ""
#     new_post = len(Post.query.filter(Post.id > g.user.last_post).all()) or ""
#
#     return render_template('pictures.html', user_count=user_count,
#                            new_message=new_message, new_post=new_post)

@pictures.route('/photos')
@pictures.route('/photos/<user>')
@login_required
def pictures(user=None):
    os.chdir(app.root_path)
    if user is None:

        photo_array = glob.glob("static/images/users/" +
                                g.user.handle + "/photos/*")
        print('photos', photo_array)
        print(app.root_path, os.getcwd())
        print("static/images/users/" + g.user.handle + "/photos/*")

    else:
        photo_array = glob.glob("static/images/users/" + user + "/photos/*")
        print('photos', photo_array)
        print(app.root_path, os.getcwd())
        print("static/images/users/" + user + "/photos/*")

    user_count = len(User.query.all())
    new_message = len(Message.query.filter
                      (Message.recipient == g.user.handle).filter
                      (Message.read is False).all()) or ""
    new_post = len(Post.query.filter(Post.id > g.user.last_post)
                   .all()) or ""

    return render_template('pictures.html', user_count=user_count,
                           new_message=new_message, new_post=new_post,
                           photo_array=photo_array)

app/pictures/templates/pictures.html
{% extends "layout.html" %}
	{% block title %}Photos{% endblock %}
	{% block menutabs %}
 	<li><a href="{{ url_for('home.home') }}">Home</a></li>
	<li><a href="{{ url_for('members.members') }}">Family</a></li>
    <li><a href="{{ url_for('messages.messages') }}">Messages</a></li>
	<li class="active"><a href="{{ url_for('pictures.pictures') }}">Albums</a></li>
	<li><a href="{{ url_for('calendar.calendar') }}">Calendar</a></li>
	{% endblock %}

{% block body %}
<div class="row">
<div class="col-xs-8">

    <h3>Photos by you</h3>

  <!-- <div class="grid">
    <div class="grid-sizer"></div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/orange-tree.jpg" />
    </div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/submerged.jpg" />
    </div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/look-out.jpg" />
    </div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/one-world-trade.jpg" />
    </div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/drizzle.jpg" />
    </div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/cat-nose.jpg" />
    </div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/contrail.jpg" />
    </div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/golden-hour.jpg" />
    </div>
    <div class="grid-item">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/flight-formation.jpg" />
    </div>
  </div> -->
  <div class="grid">
    <div class="grid-sizer"></div>
      {% for photo_array in photo_array %}
        <div class="grid-item">
            <img src="{{ photo_array }}" />
        </div>
      {% endfor %}
    </div>
  <script>
  var $grid = $('.grid').isotope({
    // options...
  });
  // layout Isotope after each image loads
  $grid.imagesLoaded().progress( function() {
    $grid.isotope('layout');
  });
  </script>

  </div>





<div class="col-xs-4 right-column">
	<div class="row">
		<div class="col-xs-12 text-center palette-peter-river">
		<p></p>
			<img class="profpic" src="/static/images/users/{{ g.user.handle }}/{{ g.user.handle }}.jpg">
		</div>
	</div>
<div class="row">
	<div class="col-xs-12 text-center palette-peter-river">
		<h6>{{ g.user.first_name }} {{ g.user.last_name }}</h6>
		<small>{{ g.user.handle }}</small>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 text-center palette-belize-hole">
		<div class="row">
			<div class="col-xs-6">
				Photos: {{ post_count }}
			</div>
			<div class="col-xs-6">
				Family: {{ user_count }}
			</div>
		</div>
	</div>
</div>
<p>
</div>
{% endblock %}