app/members/__init__.py
from flask import Blueprint

members = Blueprint('members', __name__, template_folder='templates')

import views

app/members/views.py
from flask import Blueprint, render_template, g
from flask_login import current_user, login_required, login_user, \
    logout_user

from app import app
from app.members import members
from app.models import User, Message, Post


@members.route('/members')
@login_required
def members():
    users = User.query.order_by('last_name asc').all()
    user_count = len(User.query.all())
    user_post_count = len(Post.query.filter_by(author=g.user).all())

    new_message = len(Message.query.filter(Message.recipient == g.user.handle)
                      .filter(Message.read is False).all()) or ""
    new_post = len(Post.query.filter(Post.id > g.user.last_post).all()) or ""

    return render_template("members.html", post_count=user_post_count,
                           all_users=users, user_count=user_count, user=users,
                           new_message=new_message, new_post=new_post)

app/members/templates/members.html
{% extends "layout.html" %}
	{% block title %}Members{% endblock %}
	{% block menutabs %}
 	<li><a href="{{ url_for('home.home') }}">Home</a></li>
	<li class="active"><a href="{{ url_for('members.members') }}">Family</a></li>
  <li><a href="{{ url_for('messages.messages') }}">Messages</a></li>
	<li><a href="{{ url_for('pictures.pictures') }}">Albums</a></li>
	<li><a href="{{ url_for('calendar.calendar') }}">Calendar</a></li>
	{% endblock %}

{% block body %}
<div class="row">
	<div class="col-xs-8">
		<div class="row">
			<div class="col-xs-3">
			</div>
	</div>
<p>
{% for user in all_users %}
<div class="row well post">
	<div class="col-xs-3">
		<h1></h1>
		<img src="static/images/users/{{ user.handle }}/{{ user.handle }}.jpg" class="profpic">
	</div>
	<div class="col-xs-8">
		<p><strong><a href="/profile/{{ user.handle }}">{{ user.full_name() }}</a></strong><small> - {{ user.handle }}</small></p>
		<p><small>Email: {{ user.email }} <br> Telephone: (555)555-5555</small></p>
	<div class="row">
		<div class="col-xs-4">
			{% if g.user.handle != user.handle %}
			<a href="{{ url_for('messages.messages', recipient=user.handle) }}"><button type="submit" class="btn btn-block btn-sm btn-danger">Message</button></a>
			{% endif %}
		</div>
		<div class="col-xs-4">
			<a href="{{ url_for('pictures.pictures') }}"><button type="submit" class="btn btn-block btn-sm btn-info">Photos</button></a>
		</div>
		<div class="col-xs-4">
			<a href="/profile/{{ user.handle }}"><button type="submit" class="btn btn-block btn-sm btn-success">Profile</button></a>
		</div>
	</div>
</div>
</div>
{% endfor %}
</div>
<div class="col-xs-4 right-column">
	<div class="row">
		<div class="col-xs-12 text-center palette-peter-river">
		<p></p>
			<img class="profpic" src="/static/images/users/{{ g.user.handle }}/{{ g.user.handle }}.jpg">
		</div>
	</div>
<div class="row">
	<div class="col-xs-12 text-center palette-peter-river">
		<h6>{{ g.user.first_name }} {{ g.user.last_name }}</h6>
		<small>{{ g.user.handle }}</small>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 text-center palette-belize-hole">
		<div class="row">
			<div class="col-xs-6">
				Posts: {{ post_count }}
			</div>
			<div class="col-xs-6">
				Family: {{ user_count }}
			</div>
		</div>
	</div>
</div>
<p>

{% endblock %}