app/calendar/__init__.py
from flask import Blueprint

calendar = Blueprint('calendar', __name__, template_folder='templates')

import views

app/calendar/views.py
from flask import Blueprint, render_template, g
from flask_login import current_user, login_required, login_user, \
    logout_user

from app import app
from app.calendar import calendar
from app.models import User, Message, Post


@app.before_request
def before_request():
    g.user = current_user


@calendar.route('/calendar')
@login_required
def calendar():
    user_count = len(User.query.all())
    new_message = len(Message.query.filter(Message.recipient == g.user.handle)
                      .filter(Message.read is False).all()) or ""
    new_post = len(Post.query.filter(Post.id > g.user.last_post).all()) or ""

    return render_template('calendar.html', user_count=user_count,
                           new_message=new_message, new_post=new_post)

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__, template_folder='templates')

import views

app/home/views.py
from flask import Blueprint, render_template, g, Markup, redirect, url_for, \
    flash
from flask_login import current_user, login_required, login_user, \
    logout_user
from flask_sqlalchemy import SQLAlchemy
from autolink import linkify
from datetime import datetime

from app import db
from app.forms import PostForm
from app.utils import timesince
from app.models import Post, User, Message
from app.home import home as mod


@mod.before_request
def before_request():
    g.user = current_user


@mod.route('/')
# @login_required
def home():
    post = Post.query.order_by('pub_date desc').all()

    users = len(User.query.all())
    latest_post = Post.query.order_by('id desc').first()
    g.user.last_post = latest_post.id
    db.session.commit()

    user_post_count = len(Post.query.filter_by(author=g.user).all())
    new_message = len(Message.query.filter(Message.recipient == g.user.handle)
                      .filter(Message.read is False).all()) or ""
    new_post = len(Post.query.filter(Post.id > g.user.last_post).all()) or ""

    return render_template("home.html", post=post, post_count=user_post_count,
                           users=users, new_message=new_message,
                           new_post=new_post)


@mod.route('/home/post', methods=['POST'])
# @login_required
def new_post():
    form = PostForm()
    content = form.content.data
    content = Markup(content).striptags()
    content = linkify(content)

    if len(content) > 0:
        post = Post(content=content)
        post.author = g.user
        post.pub_date = datetime.utcnow()
        post.read = True

        db.session.add(post)
        db.session.commit()
    else:
        flash("Status updates cannot be blank.", "warning")

    return redirect(url_for('home.home'))

app/members/__init__.py
from flask import Blueprint

members = Blueprint('members', __name__, template_folder='templates')

import views

app/members/views.py
from flask import Blueprint, render_template, g
from flask_login import current_user, login_required, login_user, \
    logout_user

from app import app
from app.members import members
from app.models import User, Message, Post


@members.route('/members')
@login_required
def members():
    users = User.query.order_by('last_name asc').all()
    user_count = len(User.query.all())
    user_post_count = len(Post.query.filter_by(author=g.user).all())

    new_message = len(Message.query.filter(Message.recipient == g.user.handle)
                      .filter(Message.read is False).all()) or ""
    new_post = len(Post.query.filter(Post.id > g.user.last_post).all()) or ""

    return render_template("members.html", post_count=user_post_count,
                           all_users=users, user_count=user_count, user=users,
                           new_message=new_message, new_post=new_post)

app/messages/__init__.py
from flask import Blueprint

messages = Blueprint('messages', __name__, template_folder='templates')

import views

app/messages/views.py
from flask import Blueprint, render_template, g, Markup, redirect, url_for, \
    flash
from flask_login import current_user, login_required, login_user, \
    logout_user
from autolink import linkify
from datetime import datetime

from app import app, db
from app.messages import messages as mod
from app.models import User, Message, Post
from app.forms import MessageForm


@mod.before_request
def before_request():
    g.user = current_user


@mod.route('/check_messages')
@login_required
def notify_messages():
    messages = len(Message.query.filter(Message.recipient == g.user.handle)
                   .filter(Message.read is False).all()) or ""
    data = {"messages": messages}
    return jsonify(data)


@mod.route('/display_messages/<cid>')
@login_required
def show_messages(cid):
    messages = len(Message.query.filter(Message.cid == cid)
                   .order_by('pub_date asc').filter(Message.read is False)
                   .all())
    data = {"messages": messages}
    return jsonify(data)


def mark_read(messages, message_cid):
    for message in messages:
        if message.recipient == g.user.handle:
            message.read = True
            db.session.commit()


@mod.route('/get_cid')
def get_cid():
    users = User.query.all()
    cids = {}
    for user in users:
        message_cid_list = sorted([str(g.user.id), str(user.id)])
        message_cid_list.insert(1, 'm')
        cids.update({user.id: ''.join(message_cid_list)})
    print(cids)
    return jsonify(cids)


@mod.route('/messages')
@mod.route('/messages/<recipient>')
@login_required
def messages(recipient=None):
    if recipient is None:
        lastmessage = Message.query.filter(Message.recipient ==
                                           g.user.handle).order_by(
                                               'pub_date desc').first()

        if lastmessage is not None:
            return redirect(url_for('messages.messages',
                                    recipient=lastmessage.author))
            # recipient = lastmessage.author
    recipient_search = User.query.filter(User.handle == recipient).first()

    if recipient_search is not None:
        message_cid_list = sorted([str(g.user.id), str(recipient_search.id)])
        message_cid_list.insert(1, 'm')
        message_cid = ''.join(message_cid_list)

        messages = Message.query.filter(Message.cid ==
                                        message_cid).order_by(
                                            'pub_date asc').all()
        read_message = mark_read(messages, message_cid)

    else:
        messages = []
    users = len(User.query.all())
    user = User.query.filter(User.handle !=
                             g.user.handle).order_by('last_name asc').all()

    new_message = len(Message.query.filter(Message.recipient == g.user.handle)
                      .filter(Message.read is False).all()) or ""

    new_post = len(Post.query.filter(Post.id > g.user.last_post).all()) or ""

    return render_template("messages.html", user=user, recipient=recipient,
                           messages=messages, users=users,
                           new_message=new_message, new_post=new_post,
                           read_message=read_message, message_cid=message_cid)


# @mod.route('/messages/<recipient>/send', methods=['POST'])
# @login_required
# def new_message(recipient):
    # form = MessageForm()
    # content = form.content.data
    # content = Markup(content).striptags()
    # content = linkify(content)
    #
    # recipient_search = User.query.filter(User.handle == recipient).first()
    # recipient_id = recipient_search.id
    # message_cid_list = sorted([str(g.user.id), str(recipient_id)])
    # message_cid_list.insert(1, 'm')
    # message_cid = ''.join(message_cid_list)
    #
    # if len(content) > 0:
    #     message = Message(content=content)
    #     message.id = len(Message.query.all())+1
    #     message.cid = message_cid
    #     message.author = g.user.handle
    #     message.pub_date = datetime.utcnow()
    #     message.recipient = recipient
    #
    #     db.session.add(message)
    #     db.session.commit()

    # else:
    #     flash("Messages cannot be blank.", "danger")

    # return ('', 204)
# return redirect(url_for('messages.messages', recipient=recipient))

app/pictures/__init__.py
from flask import Blueprint

pictures = Blueprint('pictures', __name__, template_folder='templates')

import views

app/pictures/views.py
from flask import Blueprint, render_template, g
from flask_login import current_user, login_required, login_user, \
    logout_user
import glob
import os

from app import app
from app.pictures import pictures
from app.models import User, Message, Post


@pictures.before_request
def before_request():
    g.user = current_user


# @pictures.route('/photos')
# @login_required
# def pictures():
#     user_count = len(User.query.all())
#     new_message = len(Message.query.filter(Message.recipient == g.user.handle).filter(Message.read is False).all()) or ""
#     new_post = len(Post.query.filter(Post.id > g.user.last_post).all()) or ""
#
#     return render_template('pictures.html', user_count=user_count,
#                            new_message=new_message, new_post=new_post)

@pictures.route('/photos')
@pictures.route('/photos/<user>')
@login_required
def pictures(user=None):
    os.chdir(app.root_path)
    if user is None:

        photo_array = glob.glob("static/images/users/" +
                                g.user.handle + "/photos/*")
        print('photos', photo_array)
        print(app.root_path, os.getcwd())
        print("static/images/users/" + g.user.handle + "/photos/*")

    else:
        photo_array = glob.glob("static/images/users/" + user + "/photos/*")
        print('photos', photo_array)
        print(app.root_path, os.getcwd())
        print("static/images/users/" + user + "/photos/*")

    user_count = len(User.query.all())
    new_message = len(Message.query.filter
                      (Message.recipient == g.user.handle).filter
                      (Message.read is False).all()) or ""
    new_post = len(Post.query.filter(Post.id > g.user.last_post)
                   .all()) or ""

    return render_template('pictures.html', user_count=user_count,
                           new_message=new_message, new_post=new_post,
                           photo_array=photo_array)

app/profile/__init__.py
from flask import Blueprint

profile = Blueprint('profile', __name__, template_folder='templates')

import views

app/profile/views.py
from flask import Blueprint, render_template, g
from flask_login import current_user, login_required, login_user, \
    logout_user
from sqlalchemy import or_, and_


from app import app
from app.profile import profile
from app.models import User, Message, Post


@app.before_request
def before_request():
    g.user = current_user


@profile.route('/profile/<handle>')
@login_required
def profile(handle):
    user = User.query.filter_by(handle=handle).first()
    print("@" + user.handle)

    post = Post.query.filter(or_(Post.content.like("%@" + user.handle + "%"), Post.author_id == user.id)).order_by('pub_date desc').all()
    new_post = len(Post.query.filter(Post.id > g.user.last_post).all()) or ""

    user_count = len(User.query.all())
    user_post_count = len(Post.query.filter_by(author=user).all())
    new_message = len(Message.query.filter(Message.recipient == g.user.handle).filter(Message.read is False).all()) or ""

    return render_template("profile.html", post=post,
                           post_count=user_post_count, user_count=user_count,
                           user=user, new_message=new_message,
                           new_post=new_post)

app/templates/calendar.html
{% extends "layout.html" %}
	{% block title %}Calendar{% endblock %}
	{% block menutabs %}
 	<li><a href="{{ url_for('home') }}">Home</a></li>
	<li><a href="{{ url_for('members') }}">Family</a></li>
    <li><a href="{{ url_for('messages') }}">Messages</a></li>
	<li><a href="{{ url_for('pictures') }}">Albums</a></li>
	<li class="active"><a href="{{ url_for('calendar') }}">Calendar</a></li>
	{% endblock %}

{% block body %}
<div class="row">
<div class="col-xs-8">
<iframe src="https://www.google.com/calendar/embed?title=Upcoming%20Events&amp;showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showCalendars=0&amp;showTz=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23E3E9FF&amp;ctz=America%2FNew_York" style=" border-width:0 " width="100%" height="550" frameborder="0" scrolling="no"></iframe>
</div>

<div class="col-xs-4 right-column">
	<div class="row">
		<div class="col-xs-12 text-center palette-peter-river">	
		<p></p>
			<img class="profpic" src="/static/images/users/{{ g.user.handle }}.jpg"> 
		</div>
	</div>
<div class="row">
	<div class="col-xs-12 text-center palette-peter-river">
		<h6>{{ g.user.first_name }} {{ g.user.last_name }}</h6>
		<small>{{ g.user.handle }}</small>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 text-center palette-belize-hole">
		<div class="row">	
			<div class="col-xs-6">
				Events: {{ post_count }}
			</div>
			<div class="col-xs-6">
				Family: {{ user_count }}
			</div>
		</div>
	</div>
</div>
<p>
</div>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}
	{% block title %}Home{% endblock %}
	{% block menutabs %}
 	<li class="active"><a href="{{ url_for('home') }}">Home</a></li>
	<li><a href="{{ url_for('members') }}">Family</a></li>
  <li><a href="{{ url_for('messages') }}">Messages</a></li>
	<li><a href="{{ url_for('pictures') }}">Albums</a></li>
	<li><a href="{{ url_for('calendar') }}">Calendar</a></li>
	{% endblock %}

{% block body %}

<div class="row">
	<div class="col-xs-8"><hr>
		<div class="row post-form">
			<div class="col-xs-9">
				<form class="form-horizontal" name="input" action="/home/post" method="POST" role="form">
					<div class="control-group form-group">
      			<input type="text" content="" name="content" placeholder="What's happening right now?" class="form-control" />
				<label class="login-field-icon fui-chat" style="border-color: transparent transparent transparent;" for="login-pass"></label>
    			</div>
  			</div>
  				<div class="col-xs-3">
    				<button type="submit" class="btn btn-block btn-lg btn-info">Post</button>
  				</div>
				</form>

			</div>
<hr>

{% for post in post %}
<div class="row well post">
	<div class="col-xs-2">
		<img src="static/images/users/{{ post.author.handle }}.jpg" class="profpic">
	</div>
	<div class="col-xs-10">{% if g.user.handle == post.author.handle %}
		<strong><a href="/profile/{{ post.author.handle }}">Me</a></strong><small> - </small><small class="smalltext"> {{ post.pub_date|timesince(post.pub_date) }}</small>
						{% else %}
		<strong><a href="/profile/{{ post.author.handle }}">{{ post.author.full_name() }}</a></strong><small> - </small><small class="smalltext"> {{ post.pub_date|timesince(post.pub_date) }}</small>
					{% endif %}
		<p class="post_content">{{ post.content|safe }}</p>
	</div>
</div>
{% endfor %}

</div>
<div class="col-xs-4 right-column">
	<div class="row">
		<div class="col-xs-12 text-center palette-peter-river">
		<p></p>
			<img class="profpic" src="/static/images/users/{{ g.user.handle }}.jpg">
		</div>
	</div>
<div class="row">
	<div class="col-xs-12 text-center palette-peter-river">
		<h6>{{ g.user.first_name }} {{ g.user.last_name }}</h6>
		<small>{{ g.user.handle }}</small>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 text-center palette-belize-hole">
		<div class="row">
			<div class="col-xs-6">
				Posts: {{ post_count }}
			</div>
			<div class="col-xs-6">
				Family: {{ users }}
			</div>
		</div>
	</div>
</div>


{% endblock %}

app/templates/layout.html
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
		<link href="/static/css/bootstrap.css" rel="stylesheet">
		<link href="/static/css/flat-ui.css" rel="stylesheet">
    <link href="/static/css/demo.css" rel="stylesheet">
    <link href="/static/css/grid.css" rel="stylesheet">
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
	  <script src="/static/js/jquery.min.js"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.js"></script>
    <script src="/static/js/jquery.isotope.perfectmasonry.js"></script>
  </head>
  <body>



		<div class="col-xs-12">
     <div class="navrow row">
       <nav class="navbar navbar-inverse navbar-embossed" role="navigation">
		 	       <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
                <span class="sr-only">Toggle navigation</span>
              </button>
            </div>
					<div class="col-lg-1">
						<a href="{{ url_for('home.home') }}"><h6 style="color: white;"><strong>Kinclan</strong></h6></a>
					</div>

						<!-- Notification Icons, black to show nothing, 1 space to show just icon, and space then number to show number of notifications -->


					<div class="col-lg-5">
					  <ul class="nav navbar-nav navbar-left" style="margin-top: 15px; margin-left: 25px;">
						<li><a href="{{ url_for('messages.messages') }}" class="b" style="padding: 3px;">
							<div class="label label-danger glyphicon glyphicon-envelope" id="refresh">
								{{ new_message }}
							</div></a></li>

						<li><a href="{{ url_for('home.home') }}" class="b" style="padding: 2px;">
							<div class="label label-info glyphicon glyphicon-comment">
								{{ new_post }}
							</div></a></li>

						<li><a href="{{ url_for('calendar.calendar') }}" class="b" style="padding: 2px;">
							<div class="label label-success glyphicon glyphicon-calendar"> </div></a></li>
					  </ul>
												<!-- Add notification updates here |^| -->
					</div>
					<div clas="col-lg-5">
						<ul class="nav navbar-nav navbar-right">
							{% if g.user == None or g.user.is_authenticated == False %}
                <li><a href="/login">Login</a></li>
								<li><a href="{{ url_for('auth.login') }}">Sign Up!</a></li>
							{% endif%}{% if g.user != None and g.user.is_authenticated %}
								<li><a href="{{ url_for('profile.profile', handle=g.user.handle) }}">{{ g.user.full_name() }}</a></li>
								<li><a href="{{ url_for('profile.profile', handle=g.user.handle) }}">Settings</a></li>
								<li><a href="/logout">Logout</a></li>
								{% endif %}
                  </ul>
					</div>
       </nav><!-- /navbar -->

					<div class="row">
					<div class="col-xs-12">
          <nav class="navbar2 menu2" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
                <span class="sr-only">Toggle navigation</span>
              </button>

					</div>
			<div class="row">
			  									       <div class="container">
						  <div class="col-lg-8" style="padding: 0px; margin-left: 5px;">

              <ul class="nav nav-tabs">{% block menutabs %}{% endblock %}
					</ul>
					</div>
						<form class="form-horizontal" role="form">
							<div class="col-lg-4 login-form" style="padding: 0px; margin-right: -20px;">
								<input align="right" type="text" class="form-control" placeholder="Search posts and people"/>
                            	<label class="login-field-icon fui-search" style="border-color: transparent transparent transparent;" for="login-pass"></label>
							</div>
						</form>

          </nav><!-- /navbar -->
				 </div>
        </div>
      </div>


<div class="inner-content">

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-dismissable alert{% if category != 'message'%}-{{ category }}{% endif %}{% if category == 'message' %}-warning{% endif %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>{{ message }}</strong>
    </div>

    {% endfor %}
  {% endif %}
{% endwith %}
	       <div class="container">
    {% block body %}{% endblock %}
    </div>
</div>
</div>

    <script src="/static/js/jquery-ui-1.10.3.custom.min.js"></script>

    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/bootstrap-select.js"></script>
    <script src="/static/js/bootstrap-switch.js"></script>
    <script src="/static/js/flatui-checkbox.js"></script>
    <script src="/static/js/flatui-radio.js"></script>
    <script src="/static/js/jquery.tagsinput.js"></script>
    <script src="/static/js/jquery.placeholder.js"></script>
	  <script>var objDiv = document.getElementById("message-scroll");
			objDiv.scrollTop = objDiv.scrollHeight;
    </script>

      <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
            // Use a "/test" namespace.
            // An application can open a connection on multiple namespaces, and
            // Socket.IO will multiplex all those connections on a single
            // physical channel. If you don't care about multiple channels, you
            // can set the namespace to an empty string.
            namespace = '/test';
            // Connect to the Socket.IO server.
            // The connection URL has the following format:
            //     http[s]://<domain>:<port>[/<namespace>]
            var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + namespace);
            // Event handler for new connections.
            // The callback function is invoked when a connection with the
            // server is established.
            socket.on('connect', function() {
                socket.emit('my_event', {data: 'I\'m connected!'});
                socket.emit('join', {room: "{{ g.user.handle }}"});
                return false;
            });
            // Event handler for server sent data.
            // The callback function is invoked whenever the server emits data
            // to the client. The data is then displayed in the "Received"
            // section of the page.
            socket.on('my_response', function(msg) {
                $('#log').append('<br>' + $('<div/>').text('Received #' + msg.count + ': ' + msg.data).html());
            });

            // Update socket_messages div in messages.html to automatically add
            // new messages.
            //socket.on('room_message', function(msg) {
            //    $('#socket_messages').append('<br>' + $('<div/>').text(msg.recipient + ': ' + msg.data).html());
            //    var objDiv = document.getElementById("message-scroll");
            //    objDiv.scrollTop = objDiv.scrollHeight;
            //});


            socket.on('room_message', function(msg) {
              var audio = new Audio('../static/audio/notification.mp3');
              audio.play();
              if (msg.author[0] == '{{ recipient }}') {
                console.log('take 1')
                $('#socket_messages').append(
                  '<div class="row"> \
        					  <div class="col-xs-11"> \
        						  <small><p class="smalltext" align="right">Just Now | '
                      + $('<div/>').text(msg.author[0]).html() + ' said:</p></small> \
        						  <p class="post_content" align="right">' + $('<div/>').text(msg.data).html() + '</p> \
        					  </div> \
        					  <div class="col-xs-1"> \
        						  <img src="../static/images/users/'
                      + $('<div/>').text(msg.author[0]).html() + '/' + $('<div/>').text(msg.author[0]).html() + '.jpg" class="smallprofpic"> \
        					  </div> \
        				  </div>'
                );
              } else if (msg.author[0] == '{{ g.user.handle }}') {
                 $('#socket_messages').append(
                   '<div class="row"> \
                     <div class="col-xs-1"> \
                       <img src="../static/images/users/'
                       + $('<div/>').text(msg.author[0]).html() + '/' + $('<div/>').text(msg.author[0]).html() + '.jpg" class="smallprofpic"> \
                     </div> \
        			 		  <div class="col-xs-11"> \
        			 			  <small><p class="smalltext" align="left">Just Now |  \
                      you said:</p></small> \
        			 			  <p class="post_content text-info" align="left">' + $('<div/>').text(msg.data).html() + '</p> \
        			 		  </div> \
        			 	  </div>'
                 );
                 document.getElementById("room_data").value = "";
               }

              var objDiv = document.getElementById("message-scroll");
              objDiv.scrollTop = objDiv.scrollHeight;
            });

            // Interval function that tests message latency by sending a "ping"
            // message. The server then responds with a "pong" message and the
            // round trip time is measured.
            var ping_pong_times = [];
            var start_time;
            window.setInterval(function() {
                start_time = (new Date).getTime();
                socket.emit('my_ping');
            }, 1000);
            // Handler for the "pong" message. When the pong is received, the
            // time from the ping is stored, and the average of the last 30
            // samples is average and displayed.
            socket.on('my_pong', function() {
                var latency = (new Date).getTime() - start_time;
                ping_pong_times.push(latency);
                ping_pong_times = ping_pong_times.slice(-30); // keep last 30 samples
                var sum = 0;
                for (var i = 0; i < ping_pong_times.length; i++)
                    sum += ping_pong_times[i];
                $('#ping-pong').text(Math.round(10 * sum / ping_pong_times.length) / 10);
            });
            // Handlers for the different forms in the page.
            // These accept data from the user and send it to the server in a
            // variety of ways
            $('form#emit').submit(function(event) {
                socket.emit('my_event', {data: $('#emit_data').val()});
                return false;
            });
            $('form#broadcast').submit(function(event) {
                socket.emit('my_broadcast_event', {data: $('#broadcast_data').val()});
                return false;
            });
            $('form#join').submit(function(event) {
                socket.emit('join', {room: $('#join_room').val()});
                return false;
            });
            $('form#leave').submit(function(event) {
                socket.emit('leave', {room: $('#leave_room').val()});
                return false;
            });
              $('form#send_room').submit(function(event) {
                  socket.emit('my_room_event', author=['{{ g.user.handle }}', '{{ g.user.id }}'], recipient='{{ recipient }}',
                    {room: '{{ recipient }}', data: $('#room_data').val()});
                  socket.emit('my_room_event', author=['{{ g.user.handle }}', '{{ g.user.id }}'], recipient='{{ recipient }}',
                    {room: '{{ g.user.handle }}', data: $('#room_data').val()});
                  return false;
            });
            $('form#close').submit(function(event) {
                socket.emit('close_room', {room: $('#close_room').val()});
                return false;
            });
            $('form#disconnect').submit(function(event) {
                socket.emit('disconnect_request');
                return false;
            });
        });
    </script>
    <h1>Flask-SocketIO Test</h1>
    <p>Async mode is: <b>{{ async_mode }}</b></p>
    <p>Average ping/pong latency: <b><span id="ping-pong"></span>ms</b></p>
    <h2>Send:</h2>
    <form id="emit" method="POST" action='#'>
        <input type="text" name="emit_data" id="emit_data" placeholder="Message">
        <input type="submit" value="Echo">
    </form>
    <form id="broadcast" method="POST" action='#'>
        <input type="text" name="broadcast_data" id="broadcast_data" placeholder="Message">
        <input type="submit" value="Broadcast">
    </form>
    <form id="join" method="POST" action='#'>
        <input type="text" name="join_room" id="join_room" placeholder="Room Name">
        <input type="submit" value="Join Room">
    </form>
    <form id="leave" method="POST" action='#'>
        <input type="text" name="leave_room" id="leave_room" placeholder="Room Name">
        <input type="submit" value="Leave Room">
    </form>
    <!-- <form id="send_room" method="POST" action='#'>
        <input type="text" name="room_name" id="room_name" placeholder="Room Name">
        <input type="text" name="room_data" id="room_data" placeholder="Message">
        <input type="submit" value="Send to Room">
    </form> -->
    <form id="close" method="POST" action="#">
        <input type="text" name="close_room" id="close_room" placeholder="Room Name">
        <input type="submit" value="Close Room">
    </form>
    <form id="disconnect" method="POST" action="#">
        <input type="submit" value="Disconnect">
    </form>
    <h2>Receive:</h2>
    <div id="log"></div>


</div>
  </body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block body %}

<div class="login">
	<form id="loginform" class="form-horizontal" role="form" action="{{ url_for('login') }}" method="post">
        <div class="login-screen">
          <div class="login-icon">
            <p>Welcome :)</p>
          </div>

          <div class="login-form">
            <div class="control-group">
              <input id="login-username" type="text" class="form-control" name="email" value="" placeholder="email">
              <label class="login-field-icon fui-user" for="login-name"></label>
            </div>

            <div class="control-group">
              <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
              <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>

            <button class="btn btn-inverse btn-large btn-block" type="submit">Login</button>
            <a class="login-link" href="#">Lost your password?</a>
          </div>
        </div>
				</form>
      </div>



{% endblock %}

app/templates/pictures.html
{% extends "layout.html" %}
	{% block title %}Photos{% endblock %}
	{% block menutabs %}
 	<li><a href="{{ url_for('home') }}">Home</a></li>
	<li><a href="{{ url_for('members') }}">Family</a></li>
    <li><a href="{{ url_for('messages') }}">Messages</a></li>
	<li class="active"><a href="{{ url_for('pictures') }}">Albums</a></li>
	<li><a href="{{ url_for('calendar') }}">Calendar</a></li>
	{% endblock %}

{% block body %}
<div class="row">
<div class="col-xs-8">



</div>

<div class="col-xs-4 right-column">
	<div class="row">
		<div class="col-xs-12 text-center palette-peter-river">	
		<p></p>
			<img class="profpic" src="/static/images/users/{{ g.user.handle }}.jpg"> 
		</div>
	</div>
<div class="row">
	<div class="col-xs-12 text-center palette-peter-river">
		<h6>{{ g.user.first_name }} {{ g.user.last_name }}</h6>
		<small>{{ g.user.handle }}</small>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 text-center palette-belize-hole">
		<div class="row">	
			<div class="col-xs-6">
				Photos: {{ post_count }}
			</div>
			<div class="col-xs-6">
				Family: {{ user_count }}
			</div>
		</div>
	</div>
</div>
<p>
</div>
{% endblock %}